site_name: OceanHackWeek Resources
nav:
    - Overview: index.md
    - Code of Conduct: conduct.md
    - Logistics: logistics.md
    - Schedule: schedule.md
    - Hack Projects: 
      - Project Overview: projects/overview.md
      - Hacking at OHW20: projects/steps.md
    - Pre-event Preparation:
      - Python Requirements: preweek/python.md
      - Git & GitHub Setup: preweek/github.md
    # - Tutorials:
      # - GitHub: tutorials/github.md
      # - git: tutorials/git.md
      # - Jupyter: tutorials/jupyterhub.md
      # - Conda: tutorials/conda.md
      # - Numpy: numpy.md
      # - Pandas: pandas.md
theme: 
    name: readthedocs
    collapse_by_default: false
    highlightjs: true
plugins:
    - search
    - markdownextradata
extra:
  hackweek:
    name: OceanHackWeek Resources
    web_url: https://oceanhackweek.github.io/ohw-learning-resources
    slack_url: https://oceanhackweek.slack.com
    github_org_url: https://github.com/oceanhackweek/
    email: oceanhkw@uw.edu
    admin_contact: Emilio Mayorga
markdown_extensions:
  - admonition
repo_url: https://github.com/oceanhackweek/ohw-learning-resources

extra_css:
    - extra.css