site_name: RAPID Learning Resources
repo_url: https://github.com/rapid-research/learning-resources/

nav:
  - Overview: index.md
  - Code of Conduct: conduct.md
  - Logistics: 
    - logistics/overview.md
    - schedule.md
    - Getting Help: logistics/getting_help.md
  - Readiness & Preparation:
    - Terms and Language: canaryopera/terms.md
    - Git: prep/git.md
    - GitHub: prep/github.md
    - Jupyter and the Hub: prep/jupyterhub.md
    # - Conda, Python, R: prep/conda.md
    # - Python Requirements: preweek/python.md
    # - Numpy: numpy.md
    # - Pandas: pandas.md
  - Tutorials:
    - Getting Started: tutorials/getting_started.md
    # - Data Access in Python: tutorials/github.md
  - Projects: 
    - Project Overview: projects/overview.md
    - Hackable Projects: projects/steps.md

theme: 
  name: readthedocs
  collapse_by_default: false
  highlightjs: true

plugins:
  - search
  - markdownextradata

markdown_extensions:
  - admonition

extra_css:
  - extra.css

extra:
  hackweek:
    name: RAPID Hack
    web_url: https://rapid-research.github.io/learning-resources/
    slack_url: https://waterhackweek.slack.com
    github_org_url: https://github.com/rapid-research/
    jupyterhub_url: https://jupyter.cuahsi.org 
    email: waterhackweek@uw.edu
    admin_contact: Christina Bandaragoda

