site_name: OceanHackWeek Resources
repo_url: https://github.com/oceanhackweek/ohw-resources

nav:
  - Overview: index.md
  - Code of Conduct: conduct.md
  - Logistics: 
    - logistics/overview.md
    - schedule.md
    - Getting Help: logistics/getting_help.md
  # - Pre-event Preparation:
  #   - Git: prep/git.md
  #   - GitHub: tutorials/github.md
  #   - git: tutorials/git.md
  #   - Jupyter: tutorials/jupyterhub.md
  #   # - Python Requirements: preweek/python.md
  #   - Conda: tutorials/conda.md
  #   # - Numpy: numpy.md
  #   # - Pandas: pandas.md
  - Tutorials:
    - Getting Started: tutorials/getting_started.md
  #   - Pre-hackweek: tutorials/prehackweek.md
  #   - Data Access in Python: tutorials/github.md
    # - GitHub: tutorials/github.md
    # - git: tutorials/git.md
    # - Jupyter: tutorials/jupyterhub.md
    # - Conda: tutorials/conda.md
    # - Numpy: numpy.md
    # - Pandas: pandas.md
  - Projects: 
    - Project Overview: projects/overview.md
    - Hacking at OHW20: projects/steps.md

theme: 
  name: readthedocs
  collapse_by_default: false
  highlightjs: true

plugins:
  - search
  - markdownextradata

markdown_extensions:
  - admonition

extra_css:
  - extra.css

extra:
  hackweek:
    name: OceanHackWeek Resources
    web_url: https://oceanhackweek.github.io/ohw-resources
    slack_url: https://oceanhackweek.slack.com
    github_org_url: https://github.com/oceanhackweek/
    email: oceanhkw@uw.edu
    admin_contact: Emilio Mayorga

