site_name: OceanHackWeek Resources
repo_url: https://github.com/oceanhackweek/ohw-resources

nav:
  - Overview: index.md
  - Code of Conduct: conduct.md
  - Logistics: logistics.md
  - Schedule: schedule.md
  - Projects: 
    - Project Overview: projects/overview.md
    - Hacking at OHW20: projects/steps.md
  # - Pre-event Preparation:
  #   - Python Requirements: preweek/python.md
  #   - Git & GitHub Setup: preweek/github.md
  # - Tutorials:
    # - GitHub: tutorials/github.md
    # - git: tutorials/git.md
    # - Jupyter: tutorials/jupyterhub.md
    # - Conda: tutorials/conda.md
    # - Numpy: numpy.md
    # - Pandas: pandas.md

theme: 
  name: readthedocs
  collapse_by_default: false
  highlightjs: true

plugins:
  - search
  - markdownextradata

markdown_extensions:
  - admonition

extra_css:
  - extra.css

extra:
  hackweek:
    name: OceanHackWeek Resources
    web_url: https://oceanhackweek.github.io/ohw-resources
    slack_url: https://oceanhackweek.slack.com
    github_org_url: https://github.com/oceanhackweek/
    email: oceanhkw@uw.edu
    admin_contact: Emilio Mayorga

