name: Test MkDocs on GH action
on:
  push:
    branches:
      - test-conda-in-ghaction

jobs:
  example-4:
    name: Ex4 Linux
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: foo
          python-version: 3.7
          channels: conda-forge
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true
          use-only-tar-bz2: true
      - shell: bash -l {0}
        run: |
          conda info
          conda install -c conda-forge mkdocs mkdocs-markdownextradata-plugin
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # build:
  #   name: Deploy docs
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: [3.7]

  #   steps:
  #     - name: Checkout master
  #       uses: actions/checkout@v2
  #     - name: Set up Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install mkdocs-markdownextradata-plugin
  #       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  #     - name: Deploy docs
  #       uses: mhausenblas/mkdocs-deploy-gh-pages@1.12
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         # CUSTOM_DOMAIN: optionaldomain.com